apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: zad2
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: appuser
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
